@php
  $emp     = $leave->employee;
  $type    = $leave->leaveType?->name ?: ucfirst($leave->type ?? 'leave');
  $from    = $leave->from_date->format('d M Y');
  $to      = $leave->to_date->format('d M Y');
  $sourceLabel = match ($leave->source) {
    'public'   => 'STAFF SELF-SERVICE PORTAL',
    'employee' => 'EMPLOYEE LOGIN',
    default    => 'ADMIN ENTRY',
  };
@endphp
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Leave Application Form — {{ $emp->name }}</title>
@include('emails._leave-styles')
</head>
<body>
<div class="wrap">

  <div class="top-bar"></div>

  <div class="erp-badge">
    <div class="crumbs">CARLANISA <span class="accent">·</span> ERP SYSTEM <span class="accent">·</span> AUTOMATED MAIL</div>
    <div class="auto-line">
      <b>{{ $emp->name }}</b> filled out the <b>Leave Application Form</b> on the
      Staff Self-Service Portal. The ERP System is automatically forwarding the completed form to HR for review.
    </div>
  </div>

  <h1 class="title">📝 Leave Application Form</h1>
  <div class="subtitle">Submitted via {{ $sourceLabel }} · {{ $leave->created_at->format('d M Y, h:i A') }}</div>

  <div class="body">

    {{-- Status pills --}}
    <div>
      <span class="pill pill-pending">Pending HR Review</span>
      @if ($leave->is_emergency)
        <span class="pill pill-emergency">⚠ Emergency</span>
      @endif
      @if ($leave->source === 'public')
        <span class="pill pill-public">Public Form</span>
      @endif
    </div>

    {{-- Section 1: Applicant --}}
    <div class="form-card">
      <div class="form-card-h">Section 1 — Applicant</div>
      <table class="form-grid">
        <tr><td class="lbl">Full Name</td>          <td class="val">{{ $emp->name }}</td></tr>
        <tr><td class="lbl">Employee Code</td>      <td class="val">{{ $emp->employee_code }}</td></tr>
        <tr><td class="lbl">Department</td>         <td class="val">{{ $emp->department ?: '—' }}</td></tr>
        <tr><td class="lbl">Designation</td>        <td class="val">{{ $emp->designation ?: '—' }}</td></tr>
        <tr><td class="lbl">Email</td>              <td class="val">{{ $emp->email ?: '—' }}</td></tr>
        <tr><td class="lbl">Phone</td>              <td class="val">{{ $emp->phone ?: '—' }}</td></tr>
      </table>
    </div>

    {{-- Section 2: Leave Details --}}
    <div class="form-card">
      <div class="form-card-h alt">Section 2 — Leave Details</div>
      <table class="form-grid">
        <tr><td class="lbl">Leave Type</td>         <td class="val">{{ $type }}</td></tr>
        <tr><td class="lbl">Reason Category</td>    <td class="val">{{ $leave->reason_category ?: '—' }}</td></tr>
        <tr><td class="lbl">From</td>               <td class="val">{{ $from }}</td></tr>
        <tr><td class="lbl">To</td>                 <td class="val">{{ $to }}</td></tr>
        <tr><td class="lbl">Total Duration</td>     <td class="val">{{ $leave->days }} day{{ $leave->days != 1 ? 's' : '' }}</td></tr>
        <tr><td class="lbl">Emergency</td>          <td class="val">{{ $leave->is_emergency ? 'YES — please review urgently' : 'No' }}</td></tr>
      </table>
      <div class="reason-box">
        <span class="h">Detailed Reason</span>
        {{ trim($leave->reason ?: '—') }}
      </div>
    </div>

    {{-- Section 3: Contact + Handover --}}
    @if ($leave->contact_during_leave || $leave->address_during_leave || $leave->handover_person || $leave->handover_notes)
    <div class="form-card">
      <div class="form-card-h">Section 3 — Contact &amp; Handover</div>
      <table class="form-grid">
        @if ($leave->contact_during_leave)
          <tr><td class="lbl">Contact Phone</td>      <td class="val">{{ $leave->contact_during_leave }}</td></tr>
        @endif
        @if ($leave->address_during_leave)
          <tr><td class="lbl">Address During Leave</td><td class="val">{{ $leave->address_during_leave }}</td></tr>
        @endif
        @if ($leave->handover_person)
          <tr><td class="lbl">Handover Person</td>    <td class="val">{{ $leave->handover_person }}</td></tr>
        @endif
      </table>
      @if ($leave->handover_notes)
        <div class="reason-box">
          <span class="h">Handover Notes</span>
          {{ $leave->handover_notes }}
        </div>
      @endif
    </div>
    @endif

    <div class="cta">
      <a href="{{ rtrim(config('app.frontend_url', 'http://localhost:3000'), '/') }}/hrm/leave">Open in ERP — Approve / Reject</a>
    </div>

  </div>

  <div class="footer">
    This is an <b>automated email</b> generated by the <span class="accent">Carlanisa ERP System</span>
    when an employee submits the Leave Application Form. Reply directly to the employee at
    <b>{{ $emp->email ?: 'no-email-on-file' }}</b> for follow-up.
  </div>

</div>
</body>
</html>
